org: nachiketin
app: nachiketinbackend
service: nachiketinbackend
package:
  individually: true
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"

plugins:
  - serverless-bundle
  - serverless-offline

functions:
  hello:
    handler: handler.initialize
    events:
      - http:
          path: hello
          method: post
          cors: true

  helloerror:
    handler: handler.errorhello
    events:
      - http:
          path: helloerror
          method: post
          cors: true
