org: nachiketin
app: nachiketinbackend
service: nachiketinbackend

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
