org: nachiketin
app: nachiketinbackend
service: nachiketinbackend
package:
  individually: true
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource: "*"

  environment:
    AWS_KEY: "${param:AWS_KEY}"
    AWS_SECRET: "${param:AWS_SECRET}"
    AWS_BUCKET: "${param:AWS_BUCKET}"
    AWS_BUCKET_JSON: "${param:AWS_BUCKET_JSON}"

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-plugin-warmup

aliases:
  - Lib: Library

functions:
  hello:
    warmup: true
    handler: handler.initialize
    events:
      - http:
          path: hello
          method: post
          cors: true

  helloerror:
    handler: handler.errorhello
    events:
      - http:
          path: helloerror
          method: post
          cors: true
